### ISSUE TITLE
remove use of valid_thru

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#103]
The field valid_thru has been removed from the frontend (https://github.com/orgs/bahnzumberg/projects/2/views/1?pane=issue&itemId=60762466). Now it has to be removed from the backend as well.

Last step: Remove from table and from the load (https://github.com/orgs/bahnzumberg/projects/2/views/1?pane=issue&itemId=60762838)

**Comment by Falsal** [comment]
done in tours.js
