### ISSUE TITLE
Cleanup: Remove outdated columns

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#11]
Depending on https://github.com/orgs/bahnzumberg/projects/2/views/1?pane=issue&itemId=31349270 the columns "internal_status" and "connection_url", "return_url" in table **fahrplan** should be removed. 
In table **tours** the column "children" and "internal_status" should be removed. If "publishing_date" is not used, remove it too.

**Comment by Falsal** [comment]
Faris will do the "children" and rest will be done by Martin

**Comment by Falsal** [comment]
@martinheppner : 
sync.js : check function mergeToursWithFahrplan and cities const in line 607; cities is not being used, either delete it or use it somewhere inside the function .
