### ISSUE TITLE
pdf download not working

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-api#116]
None of the domains (UAT nor PROD) are downloading the file, there is an axios error with a 404 . The path passed to the call is the correct one. 
Suspicion of file directory mismatch.

**Comment by martinheppner** [comment]
I looked into it yesterday. I could not find the problem. Maybe I am missing something, when the PDF is created? Maybe we take a look together at these procedures?

**Comment by Falsal** [comment]
Sure, just to add the screenshots of the issue here:
Looks like the gpx files are not being found :

![Image](https://github.com/bahnzumberg/zuugle-api/assets/70447836/6ee40060-5c23-4aa0-b70d-ca34e1e164ce)
![Image](https://github.com/bahnzumberg/zuugle-api/assets/70447836/ca3173d0-a2ff-4804-99bb-b4dd28e339ed)
![Image](https://github.com/bahnzumberg/zuugle-api/assets/70447836/7f5a6d5a-3e54-437d-9180-61e033dd5790)

**Comment by Falsal** [comment]
Looks like I found one culprit :


![Image](https://github.com/bahnzumberg/zuugle-api/assets/70447836/91d88950-cfee-4280-81be-903d5dd81a40)

**Comment by Falsal** [comment]
I created a utility function and imported it inside both tours.js and sync.js , so  this error should solved now. 
@martinheppner : can you find time to check if this is solved now ? Thank you

**Comment by martinheppner** [comment]
PDF button has been deactivated. Better it is not visible, than visible, but not working.

**Comment by Falsal** [comment]
There was one more file that needed import of the function , so now we have a pdf download on uat, but the above error of unfound gpx related files , like : Cannot GET /public/gpx-track/totour/91/10842691.gpx is still appearing in the console , will work on fixing this one as well.

**Comment by Falsal** [comment]
After a deep-dive in our Friday session , it looks like that the error appears when there are no actual data imported, i.e. the missing files could be a sync issue that occurs from crunchy  to posgres. 
example : https://www2.zuugle.at/public/gpx-track/fromtour/32/10631832.gpx
Will open a new issue to fix this bug.

**Comment by martinheppner** [comment]
But the track_key=10631832 exists in the database. It holds only two datapoints, but it exists.

```
SELECT 
*
FROM tracks
WHERE track_key=10631832
```

**Comment by martinheppner** [comment]
Maybe #102 has to do with that, as well, but it is not the cause why https://www2.zuugle.at/public/gpx-track/fromtour/32/10631832.gpx is not generated. The cause for this is, that track_key=10631832 exists on PROD, but not on UAT.

**Comment by martinheppner** [comment]
I changed the load script. Now all tracks are available.
