### ISSUE TITLE
Result ordering by language is not working

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#117]
Opening https://www.zuugle.si/suche?city=ljubljana&map=true shows me at first german tours.

![Image](https://github.com/bahnzumberg/zuugle-api/assets/105971399/fa54c473-fcf4-416c-a1d9-cb4f0b8cfa0e)

When I execute the SQL below I see that 2.278 tours are reachable from Ljubljana (column text_lang = sl ), which should be the first results. This is why we did the UNION SQLs, to maintain the language order. Something might be broken (since the map)?

```
SELECT 
COUNT(*),
t.text_lang
FROM fahrplan AS f
INNER JOIN tour AS t
ON t.hashed_url=f.hashed_url
WHERE f.city_slug='ljubljana'
GROUP BY t.text_lang
```

**Comment by diditrummer** [comment]
We have checked the code. Following two remarks:
1. When no search term is given the language of the tour seems to play no role in the ordering. Are you really sure that we had once this feature that without a search term the select language determins which tours come first?
2. Even when there is a search term the selected language is not "forced" to be on top. The search term needs to fit quite well to make a difference.
We want to talk to you about your expectations...

**Comment by martinheppner** [comment]
Completely new search SQL - one for all usecases. Very fast.
