### ISSUE TITLE
Fix code scanning alert - Type confusion through parameter tampering

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#14]
Tracking issue for:
- [ ] https://github.com/bahnzumberg/zuugle-api/security/code-scanning/17

**Comment by Falsal** [comment]
this tpe is definitly a string and in order to remove the alert , we can stringify the domain variable before passing it the method (indexOf)

**Comment by Falsal** [comment]
makes no sense to stringify "domain" , instead I added a type control else return a "AT" as a default value.
In any case, this function is not being used currently but should replace a boilerplate code inside routes/ranges
