### ISSUE TITLE
Fix code scanning alert - Incomplete string escaping or encoding

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#17]
Tracking issue for:
- [ ] https://github.com/bahnzumberg/zuugle-api/security/code-scanning/4

**Comment by Falsal** [comment]
This has been solved by following the recommendation in the link, see screenshot, this has been done in the 2 cases when search term is being used (logsearch and creating the queries)

![Image](https://github.com/bahnzumberg/zuugle-api/assets/70447836/b692b115-53b2-42f6-86d0-b00626f4a7fd)

**Comment by Falsal** [comment]
Another way to protect the logsearch is to using parameterized queries within the knex.raw call.
