### ISSUE TITLE
Is function mergeToursWithFahrplan() still needed?

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#23]
The function mergeToursWithFahrplan() is doing nothing other than updating the columns  country_at, country_de, country_ch, country_it, country_fr and country_si. Is my analysis correct? 

If yes, then we should deactivate it completely and remove the columns from the table as well.

**Comment by Falsal** [comment]
Need to check where these variables are needed , if they are really needed, will check as soon as possible

**Comment by martinheppner** [comment]
The answer is yes. It is partly needed. The country_xx thing has been removed, the rest is needed.
