### ISSUE TITLE
Enable GPX download disable feature

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#29]
Import column "allow_gpx_download" from vw_provider_to_search to enable https://github.com/orgs/bahnzumberg/projects/2?pane=issue&itemId=34295492

**Comment by benoitjoh** [comment]
Just a remark: I remember importing tracks in gpx format was possible at least two years ago. Actually the osmand app (Android 12 and 6) does only allow osf files. 
In this context I don't understand the issue. In my opinion it must be possible to exchange data in gpx as it is the most common format!

**Comment by martinheppner** [comment]
Database has been adapted by adding a new column. Sync is importing it. Now it has to be used.
