### ISSUE TITLE
Limit query to necessary columns

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#32]
In Tours.js in line 794 "const query_con = knex('fahrplan').select().where({hashed_url: tour.hashed_url, provider: tour.provider, city_slug: city});" the select should be restricted to the columns, which are really used.

**Comment by martinheppner** [comment]
connectionsExtendedWrapper

**Comment by Falsal** [comment]
Don't we need all 3 columns (hashed_url, provider and city_slug) to get any type of connection  within the table 'fahrplan' ?

**Comment by martinheppner** [comment]
Is the question still open? The ticket is closed.
