### ISSUE TITLE
API autosuggest not delivering

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#36]
Abdul just showed me with this link, taht Autosuggestion is not working from the API side (or is wrongly calöled): https://www2.zuugle.at/api/searchPhrases?search=aben&city=amstetten&language=en

![Image](https://user-images.githubusercontent.com/105971399/265010498-35b5dfac-b275-4350-8942-7a4ad99d06be.png)

**Comment by FALBZB** [comment]
done
