### ISSUE TITLE
Error: import-data-full routine

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-api#40]
After I pulled recent API changes, i get the following error when doing the import-data-full
<img width="1512" alt="Screenshot 2023-10-04 at 15 27 41" src="https://github.com/bahnzumberg/zuugle-api/assets/70447836/b83172f6-11be-419d-b9d7-931602ed4dad">

**Comment by martinheppner** [comment]
Solved by my last push to uat. Running "npm run import-data" on development is sufficient.
