### ISSUE TITLE
Data seems to be missing in itinirary 

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-api#41]
Front end seems to be impacted by changes in the API, after I pulled changes to API made last week , I am currently getting this (see screenshot)
<img width="419" alt="Screenshot 2023-10-04 at 16 06 58" src="https://github.com/bahnzumberg/zuugle-api/assets/70447836/cc8ff78f-5c15-4da8-903c-12140328132a">

**Comment by martinheppner** [comment]
Where is the screenshot from? Local dev? UAT? Prod?

Can you find this in the database? Where is it? How is it shown in the database?

**Comment by martinheppner** [comment]
The database holds this:
![image](https://github.com/bahnzumberg/zuugle-api/assets/105971399/07ce872a-085c-406f-add5-2c390926e780)

It seems to be a problem in the frontend how it is interpreting this string. Maybe the ">" is creating a problem?

**Comment by Falsal** [comment]
After import of new data, this error is not visible in 20 tests of different tours. I will suppose it is done now, we will open this issue again if it reappears .
