### ISSUE TITLE
Autosuggest feature not working without city

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#45]
Searching for "schnee" gives me autosuggestions - see first picture - when I have selected a city.
The second screenshot shows the same search for "schnee", but shows no auto suggestions.

![Image](https://user-images.githubusercontent.com/105971399/277948197-46b0aaf8-90ec-45c3-8a10-1f2d3f1ec0c4.png)

![Image](https://user-images.githubusercontent.com/105971399/277948053-581e1669-5d93-46aa-a797-23d0b0e8c206.png)

**Comment by martinheppner** [comment]
The priority of this issue is very high, because all the people, who are visiting the first time, will not return, when they are frustrated.

**Comment by Falsal** [comment]
@martinheppner : will get on it today.

**Comment by martinheppner** [comment]
The city is a string "null". It was checked if the city is null, but not if it is not "null". This has been added now. And that only lowercase strings are stored into logsearchphrase table.
