### ISSUE TITLE
Fix code scanning alert - Type confusion through parameter tampering

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#52]
Tracking issue for:
- [ ] https://github.com/bahnzumberg/zuugle-api/security/code-scanning/107

**Comment by martinheppner** [comment]
fixed by adding the following lines to searchPhrases.js

```
    let search = req.query.search;

    if (typeof search !== 'string') { 
        search = '';
        return res.status(400).json({success: false, error: 'Bad Request - no valid search term'});
    }
```

**Comment by Falsal** [comment]
As per the document within the alert itself, the if condition should check "search" for ".." : 

if (typeof search !== 'string' || search.indexOf("..") !== -1) {
