### ISSUE TITLE
Error handling, when no Tour is found for given ID

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#6]
Error handling, when no Tour is found for given ID: zuugle-api cannot handle calls with an unknown ID and crashes

**Comment by FALBZB** [comment]
I will clarify the issue and comment back here...

**Comment by FALBZB** [comment]
We agreed to leave the header with a below large font text 404 in grey and a link to the start page for his domain (normal font size)

**Comment by martinheppner** [comment]
If "id" is not in the tour table, the frontend should reroute to "/suche"

**Comment by Falsal** [comment]
@martinheppner : this should be an issue only for API, it is now completed so i will close it, and will open a new one for suchseite.
