### ISSUE TITLE
npm run import-data-full fails

### ISSUE THREAD

**Issue by TheKashe** [bahnzumberg/zuugle-api#82]
1. "p-limit": "^5.0.0", requires ESM. 

I was unable to run npm run import-data-full under 20.3.0 or 19.8. The only solution which worked was to downgrade p-limit to 3.1, which doesn't require ESM.

2. The documentation does not provide any details about TourenDB. Where can I get it?

**Comment by martinheppner** [comment]
Please follow the Readme https://github.com/bahnzumberg/zuugle-api/blob/main/README.md
