### ISSUE TITLE
Itinerary detail 3: Old columns in api not updated anymore

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#88]
![Image](https://github.com/bahnzumberg/zuugle-api/assets/87718607/ef37c6c3-6d0c-4d54-9f09-c8bf34786761)

**Comment by Falsal** [comment]
If 4 and 5 are complete then this becomes basically an alteration inside sync.js only .

**Comment by martinheppner** [comment]
We can check, if they can be removed by updating the UAT database with this:

```
UPDATE fahrplan
SET
connection_description='SHOULD NOT BE VISIBLE',
connection_description_detail='SHOULD NOT BE VISIBLE',
return_description='SHOULD NOT BE VISIBLE',
return_description_detail='SHOULD NOT BE VISIBLE'

```

**Comment by martinheppner** [comment]
@Falsal isn't this already done? I think it is. If yes, please close the ticket. Thank you.
