### ISSUE TITLE
Enhance API with id from table tours

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#96]
Enhance API with id (which is not changing) from table tours, so https://github.com/orgs/bahnzumberg/projects/2/views/1?pane=issue&itemId=59814487 can be implemented.

We add to the api the field id - additionally to provider and hashed_url.

The field id was used in the past and is already in the API. Task: To check if this assumption is correct.

**Comment by Falsal** [comment]
I verified the result of returning data; for each tour data , all 3 items are currently being returned (id, hashed_url and provider)
