### ISSUE TITLE
Sync: Put date in front of time

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#97]
The date in front of the time makes it more easy to read in a log file. Additionally it should start with the date time in the format "YYYY-MM-DD HH:MM:SS", then a space and then the text.

![Image](https://github.com/bahnzumberg/zuugle-api/assets/105971399/db9f036d-940d-4867-8eca-a067cb4a94ad)

**Comment by MananPoojara** [comment]
you can Parse the existing timestamp (HH:MM:SS) Reformat it to YYYY-MM-DD HH:MM:SS.

**Comment by MananPoojara** [comment]
i made changes you can review it #99

**Comment by martinheppner** [comment]
done for production
